# Generated by Django 3.0.4 on 2020-05-28 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200520_1433'),
        ('orders', '0004_auto_20170205_1206'),
    ]

    operations = [
    ]
