# Generated by Django 3.0.4 on 2020-05-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_merge_20200528_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='nmb',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_address',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
