# Generated by Django 3.0.4 on 2020-05-28 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_productinbasket_session_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinbasket',
            old_name='number',
            new_name='nmb',
        ),
        migrations.RenameField(
            model_name='productinorder',
            old_name='number',
            new_name='nmb',
        ),
    ]
