# Generated by Django 3.0.4 on 2020-06-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_discount',
            field=models.BooleanField(default=False),
        ),
    ]
