# Generated by Django 3.0.4 on 2020-05-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shourt_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
